# Generated by Django 4.2 on 2024-06-16 19:17

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=wagtail.fields.RichTextField(),
        ),
    ]
